version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mydb
volumes:
  mongodb-data:

